import Head from "next/head";
import Button from "@material-ui/core/Button";

import Header from "../Components/Header";
import Category from "../Components/Category";
import Grids from "../Components/Grids";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Status Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Button variant="contained">
          <img src="/menublue.svg" />
        </Button>
        <Header />
        <Category />
        <Grids />
      </div>
      <div className="flex justify-center items-center ">
        Made with ❤️ by Akshay Deosthale 😃
      </div>
    </div>
  );
}
